### ISSUE TITLE
安装fs服务端出现证书错误，求救QAQ

### ISSUE THREAD

**Issue by nendonerd** [ucoker/finalspeed#1]
Download software...
--2017-02-13 01:49:43--  https://github.com/ucoker/finalspeed/raw/master/server/finalspeed_server.zip
正在解析主机 github.com... 192.30.253.112, 192.30.253.113
正在连接 github.com|192.30.253.112|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Found
位置：https://raw.githubusercontent.com/ucoker/finalspeed/master/server/finalspeed_server.zip [跟随至新的 URL]
--2017-02-13 01:49:43--  https://raw.githubusercontent.com/ucoker/finalspeed/master/server/finalspeed_server.zip
正在解析主机 raw.githubusercontent.com... 151.101.128.133, 151.101.192.133, 151.101.64.133, ...
正在连接 raw.githubusercontent.com|151.101.128.133|:443... 已连接。
错误: 证书通用名 “www.github.com” 与所要求的主机名 “raw.githubusercontent.com” 不符。
要以不安全的方式连接至 raw.githubusercontent.com，使用‘--no-check-certificate’。
Download software failed!

**Comment by ucoker** [comment]
试试  
`wget https://github.com/ucoker/finalspeed/raw/master/server/finalspeed_server.zip`

我这边尝试是可以。输出信息：

```
wget https://github.com/ucoker/finalspeed/raw/master/server/finalspeed_server.zip
--2017-02-13 15:07:07--  https://github.com/ucoker/finalspeed/raw/master/server/finalspeed_server.zip
正在解析主机 github.com (github.com)... 192.30.253.112, 192.30.253.113
正在连接 github.com (github.com)|192.30.253.112|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 302 Found
位置：https://raw.githubusercontent.com/ucoker/finalspeed/master/server/finalspeed_server.zip [跟随至新的 URL]
--2017-02-13 15:07:09--  https://raw.githubusercontent.com/ucoker/finalspeed/master/server/finalspeed_server.zip
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.100.133
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|151.101.100.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：2370359 (2.3M) [application/zip]
正在保存至: “finalspeed_server.zip.1”
finalspeed_server.z 100%[===================>]   2.26M  2.92MB/s    in 0.8s    

2017-02-13 15:11:25 (2.92 MB/s) - 已保存 “finalspeed_server.zip.2” [2370359/2370359])
```

若还不行，请自己检查下自己的网络。这个不属于`finalspeed`或者`github`的问题。
